package com.example.account.Type;

public enum AccountResult {
    ACCOUNT_SUCCESS,
    ACCOUNT_FAILED_NO_USER_FOUND,
    ACCOUNT_FAILED_USER_HAVE_OVER_TEN_ACCOUNT,
    ACCOUNT_FAILED_USER_NOT_MATCHED,
    ACCOUNT_FAILED_ALREADY_UNREGISTED,
    ACCOUNT_FAILED_REMAIN_BALANCE,

}
