package com.example.account.Type;

public enum TransactionResult {
    TRANSACTION_SUCCESS,
    TRANSACTION_FAILED_DIFFERENCE_USER,
    TRANSACTION_FAILED_ALREADY_TERMINATED,
    TRANSACTION_FAILED_OVERBALANCE,
    TRANSACTION_FAILED_LOWERMINIMUMBALANCE,
    TRANSACTION_FAILED_NOT_OWN_ACCOUNT,
    TRANSACTION_FAILED_NOT_CORRECT_AMOUNT,
    TANSSACTION_FAILED_NOT_FOUND_TRANSACTIONID,

}
