package com.example.account.Type;

public enum TransactionResult {
    TRANSACTION_SUCCESS,
    TRANSACTION_FAILED_DIFFERENCE_USER,
    TRANSACTION_FAILED_ALREADY_UNREGISTED,
    TRANSACTION_FAILED_REQUEST_OVERBALANCE,
    TRANSACTION_FAILED_HEIGHER_THAN_MAXREQUEST,
    TRANSACTION_FAILED_LOWER_THAN_MINREQUEST,
    TRANSACTION_FAILED_NOT_OWN_ACCOUNT,
    TRANSACTION_FAILED_NOT_CORRECT_AMOUNT,
    TRANSACTION_FAILED_NOT_FOUND_TRANSACTIONID,
    TANSSACTION_FAILED_NOT_FOUND_USERID,

}
